const norm = v => String(v ?? '').toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu, ' ').trim();
const sleep = ms => new Promise(r => setTimeout(r, ms));
const listingLog = (...args) => console.log('[ListingUploader]', ...args);
let lastLocationReason = '';
let lastDealSelectionReason = '';
let ssTransactionCardValue = '';
const ssAppliedExactChoices = new Map();
const SS_CREATE_DEFAULTS = {
  category: ['\u10e3\u10eb\u10e0\u10d0\u10d5\u10d8 \u10e5\u10dd\u10dc\u10d4\u10d1\u10d0', '\u10d1\u10d8\u10dc\u10d0'],
  details: {
    '\u10d9\u10dd\u10dc\u10d3\u10d8\u10ea\u10d8\u10dd\u10dc\u10d4\u10e0\u10d8': true,
    '\u10d0\u10d8\u10d5\u10d0\u10dc\u10d8': true,
    '\u10e1\u10d0\u10e0\u10d3\u10d0\u10e4\u10d8': false,
    '\u10e1\u10d0\u10d9\u10d0\u10d1\u10d4\u10da\u10dd \u10e2\u10d4\u10da\u10d4\u10d5\u10d8\u10d6\u10d8\u10d0': true,
    '\u10da\u10d8\u10e4\u10e2\u10d8': true,
    '\u10db\u10d0\u10ea\u10d8\u10d5\u10d0\u10e0\u10d8': true,
    '\u10d0\u10d5\u10d4\u10ef\u10d8': true,
    '\u10d2\u10d0\u10e0\u10d0\u10df\u10d8': true,
    '\u10db\u10d8\u10dc\u10d8-\u10de\u10d0\u10d9\u10d4\u10e2\u10d8': false,
    '\u10ea\u10d4\u10dc\u10e2. \u10d2\u10d0\u10d7\u10d1\u10dd\u10d1\u10d0': true,
    '\u10ea\u10ee\u10d4\u10da\u10d8 \u10ec\u10e7\u10d0\u10da\u10d8': true,
    '\u10d8\u10dc\u10e2\u10d4\u10e0\u10dc\u10d4\u10e2\u10d8': true,
    '\u10e0\u10d9\u10d8\u10dc\u10d8\u10e1 \u10d9\u10d0\u10e0\u10d8': true,
    '\u10d1\u10e3\u10dc\u10d4\u10d1\u10e0\u10d8\u10d5\u10d8 \u10d0\u10d8\u10e0\u10d8': true,
    '\u10e1\u10d8\u10d2\u10dc\u10d0\u10da\u10d8\u10d6\u10d0\u10ea\u10d8\u10d0': false,
    '\u10e1\u10d0\u10d7\u10d0\u10d5\u10e1\u10dd': true,
    '\u10e2\u10d4\u10da\u10d4\u10e4\u10dd\u10dc\u10d8': true,
    '\u10e2\u10d4\u10da\u10d4\u10d5\u10d8\u10d6\u10dd\u10e0\u10d8': true,
    '\u10e1\u10d0\u10e0\u10d4\u10ea\u10ee\u10d8 \u10db\u10d0\u10dc\u10e5\u10d0\u10dc\u10d0': true,
    '\u10d3\u10d0\u10e1\u10d0\u10e8\u10d5\u10d4\u10d1\u10d8\u10d0 \u10e8\u10d8\u10dc\u10d0\u10e3\u10e0\u10d8 \u10ea\u10ee\u10dd\u10d5\u10d4\u10da\u10d4\u10d1\u10d8': true,
    'ბოლო სართული': false,
    'ჩაშენებული სამზარეულო': true
  }
};
const G = {
  transaction:['transaction','deal type','\u10d2\u10d0\u10dc\u10ea\u10ee\u10d0\u10d3\u10d4\u10d1\u10d8\u10e1 \u10e1\u10d0\u10ee\u10d4\u10dd\u10d1\u10d0','\u10d2\u10d0\u10e7\u10d8\u10d3\u10d5\u10d0 \u10e5\u10d8\u10e0\u10d0','\u10d2\u10d0\u10e0\u10d8\u10d2\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8','აირჩიეთ გარიგების ტიპი'],
  property:['property type','category','\u10e5\u10dd\u10dc\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8','\u10d9\u10d0\u10e2\u10d4\u10d2\u10dd\u10e0\u10d8\u10d0'],
  city:['city','\u10e5\u10d0\u10da\u10d0\u10e5\u10d8'], district:['district','region','neighborhood','\u10e3\u10d1\u10d0\u10dc\u10d8','\u10e0\u10d0\u10d8\u10dd\u10dc\u10d8'], location:['location','\u10db\u10d3\u10d4\u10d1\u10d0\u10e0\u10d4\u10dd\u10d1\u10d0'],
  address:['address','street','\u10db\u10d8\u10e1\u10d0\u10db\u10d0\u10e0\u10d7\u10d8','\u10e5\u10e3\u10e9\u10d0'], description:['description','comment','details','\u10d0\u10e6\u10ec\u10d4\u10e0\u10d0','\u10d9\u10dd\u10db\u10d4\u10dc\u10e2\u10d0\u10e0\u10d8'],
  price:['price','amount','\u10e4\u10d0\u10e1\u10d8'], currency:['currency','\u10d5\u10d0\u10da\u10e3\u10e2\u10d0'], area:['area','space','sqm','m2','\u10e4\u10d0\u10e0\u10d7\u10d8','\u10e4\u10d0\u10e0\u10d7\u10dd\u10d1\u10d8','\u10d9\u10d5\u10d0\u10d3\u10e0\u10d0\u10e2\u10e3\u10da\u10dd\u10d1\u10d0'],
  rooms:['rooms','room count','\u10dd\u10d7\u10d0\u10ee\u10d4\u10d1\u10d8'], bedrooms:['bedrooms','\u10e1\u10d0\u10eb\u10d8\u10dc\u10d4\u10d1\u10d4\u10da\u10d8'], balconyCount:['balcony','balcony / loggia','\u10d0\u10d8\u10d5\u10d0\u10dc\u10d8 / \u10da\u10dd\u10ef\u10d8\u10d0','\u10d0\u10d8\u10d5\u10d0\u10dc\u10d8/\u10da\u10dd\u10ef\u10d8\u10d0'], bathrooms:['bathroom','bathrooms','\u10e1\u10d5\u10d4\u10da\u10d8 \u10ec\u10d4\u10e0\u10e2\u10d8\u10da\u10d8'], floor:['floor','\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d8'], totalFloors:['total floors','floor count','\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d4\u10d1\u10d8 \u10e1\u10e3\u10da','\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d8\u10d0\u10dc\u10dd\u10d1\u10d0'],
  condition:['condition','repair','\u10db\u10d3\u10d2\u10dd\u10db\u10d0\u10e0\u10d4\u10dd\u10d1\u10d0','\u10e0\u10d4\u10db\u10dd\u10dc\u10e2\u10d8'], phone:['phone','telephone','mobile','\u10e2\u10d4\u10da\u10d4\u10e4\u10dd\u10dc\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8','\u10db\u10d4\u10e1\u10d0\u10d9\u10e3\u10d7\u10e0\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8'],
  project:['project type','\u10de\u10e0\u10dd\u10d4\u10e5\u10e2\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8','\u10de\u10e0\u10dd\u10d4\u10e5\u10e2\u10d8'], buildingStatus:['building status','\u10e1\u10e2\u10d0\u10e2\u10e3\u10e1\u10d8'],
  street:['street','\u10e5\u10e3\u10e9\u10d0'], streetNumber:['street number','house number','\u10e5\u10e3\u10e9\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8','\u10e1\u10d0\u10ee\u10da\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8'],
  elevator:['elevator','lift','\u10da\u10d8\u10e4\u10e2\u10d8'], parking:['parking','\u10de\u10d0\u10e0\u10d9\u10d8\u10dc\u10d2\u10d8'], yard:['yard','garden','\u10d4\u10d6\u10dd']
};
const TRANSACTION_VALUES = [
  '\u10d8\u10e7\u10d8\u10d3\u10d4\u10d1\u10d0',
  '\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0',
  '\u10d2\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0',
  '\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0 \u10d3\u10e6\u10d8\u10e3\u10e0\u10d0\u10d3'
];
const SS_RENTAL_PERIOD_ALIASES = ['\u10d2\u10d0\u10e5\u10d8\u10e0\u10d0\u10d5\u10d4\u10d1\u10d8\u10e1 \u10de\u10d4\u10e0\u10d8\u10dd\u10d3\u10d8','\u10e5\u10d8\u10e0\u10d8\u10e1 \u10de\u10d4\u10e0\u10d8\u10dd\u10d3\u10d8'];
const SS_RENTAL_PERIOD_VALUES = ['3 \u10d7\u10d5\u10d4','6 \u10d7\u10d5\u10d4','9 \u10d7\u10d5\u10d4','12 \u10d7\u10d5\u10d4','15 \u10d7\u10d5\u10d4','18 \u10d7\u10d5\u10d4'];
// SS.ge rentals always use this extension-owned default; it is never read from data.json.
const SS_DEFAULT_RENTAL_PERIOD = '12 \u10d7\u10d5\u10d4';
const DEFAULT_RENTAL_TYPE = 'მთლიანი ქონება';
const DEFAULT_PROJECT_TYPE = 'არასტანდარტული';
const canonicalTransaction = value => TRANSACTION_VALUES.find(candidate => norm(candidate) === norm(value));
const transactionError = value => `Transaction type "${String(value)}" could not be confirmed.`;
const dealSelectionError = value => lastDealSelectionReason === 'rental-period' ? `Rental period "${SS_DEFAULT_RENTAL_PERIOD}" could not be confirmed.` : lastDealSelectionReason === 'rental-type' ? `Rental type "${DEFAULT_RENTAL_TYPE}" could not be confirmed.` : transactionError(value);
const K = (d, ...keys) => keys.map(k => d[k]).find(v => v !== undefined && v !== null);
const KNonEmpty = (d, ...keys) => keys.map(k => d[k]).find(v => v !== undefined && v !== null && String(v).trim() !== '');
function splitAddress(address, city) {
  let raw=String(address||'').trim();
  if(city) raw=raw.replace(new RegExp('^'+String(city).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*','i'),'');
  const number=raw.match(/(?:#|\u2116)?\s*(\d+(?:[\/-]\d+)?\s*[\p{L}]?)\s*$/u)?.[1]?.replace(/\s+/g,'')||'';
  const street=raw.replace(/(?:#|\u2116)?\s*\d+(?:[\/-]\d+)?\s*[\p{L}]?\s*$/u,'').replace(/\s+/g,' ').trim();
  return {street,number};
}
function values(d) { const city=K(d,'\u10e5\u10d0\u10da\u10d0\u10e5\u10d8'); const comment=String(K(d,'\u10d9\u10dd\u10db\u10d4\u10dc\u10e2\u10d0\u10e0\u10d8')||''); const combined=String(K(d,'\u10dd\u10d7\u10d0\u10ee\u10d4\u10d1\u10d8 \u10d3\u10d0 \u10e1\u10d0\u10eb\u10d8\u10dc\u10d4\u10d1\u10d4\u10da\u10d8')||''); const parsedRooms=combined.match(/(\d+)\s*\u10dd\u10d7\u10d0\u10ee/u)?.[1]; const parsedBedrooms=combined.match(/(\d+)\s*\u10e1\u10d0\u10eb/u)?.[1]; const rawStatus=K(d,'\u10e1\u10e2\u10d0\u10e2\u10e3\u10e1\u10d8'); const buildingStatus=/(\u10d0\u10e8\u10d4\u10dc\u10d4\u10d1\u10e3\u10da\u10d8|\u10db\u10e8\u10d4\u10dc\u10d4\u10d1\u10d0\u10e0\u10d4)/u.test(String(rawStatus||''))?rawStatus:undefined; return {
  transaction:KNonEmpty(d,'\u10d2\u10d0\u10dc\u10ea\u10ee\u10d0\u10d3\u10d4\u10d1\u10d8\u10e1 \u10e1\u10d0\u10ee\u10d4\u10dd\u10d1\u10d0','\u10d2\u10d0\u10e7\u10d8\u10d3\u10d5\u10d0/\u10e5\u10d8\u10e0\u10d0'), property:K(d,'\u10e5\u10dd\u10dc\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8'), city, district:K(d,'\u10e3\u10d1\u10d0\u10dc\u10d8'), location:city,
  description:K(d,'\u10d9\u10dd\u10db\u10d4\u10dc\u10e2\u10d0\u10e0\u10d8'), price:K(d,'\u10e4\u10d0\u10e1\u10d8'), currency:K(d,'\u10d5\u10d0\u10da\u10e3\u10e2\u10d0'), area:K(d,'\u10e4\u10d0\u10e0\u10d7\u10dd\u10d1\u10d8 (\u10db\u00b2)','\u10d9\u10d5\u10d0\u10d3\u10e0\u10d0\u10e2\u10e3\u10da\u10dd\u10d1\u10d0'), rooms:parsedRooms??K(d,'\u10dd\u10d7\u10d0\u10ee\u10d4\u10d1\u10d8'), bedrooms:parsedBedrooms??K(d,'\u10e1\u10d0\u10eb\u10d8\u10dc\u10d4\u10d1\u10d4\u10da\u10d8'), balconyCount:K(d,'\u10d0\u10d8\u10d5\u10d0\u10dc\u10d8 / \u10da\u10dd\u10ef\u10d8\u10d0','\u10d0\u10d8\u10d5\u10d0\u10dc\u10d8/\u10da\u10dd\u10ef\u10d8\u10d0'), bathrooms:K(d,'\u10e1\u10d5\u10d4\u10da\u10d8 \u10ec\u10d4\u10e0\u10e2\u10d8\u10da\u10d8'), floor:K(d,'\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d8'), totalFloors:K(d,'\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d8\u10d0\u10dc\u10dd\u10d1\u10d0','\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d4\u10d1\u10d8 \u10e1\u10e3\u10da','\u10e1\u10d0\u10e0\u10d7\u10e3\u10da\u10d4\u10d1\u10d8\u10e1 \u10e0\u10d0\u10dd\u10d3\u10d4\u10dc\u10dd\u10d1\u10d0'),
  condition:K(d,'\u10db\u10d3\u10d2\u10dd\u10db\u10d0\u10e0\u10d4\u10dd\u10d1\u10d0','\u10e0\u10d4\u10db\u10dd\u10dc\u10e2\u10d8'), project:K(d,'\u10de\u10e0\u10dd\u10d4\u10e5\u10e2\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8')||'\u10d0\u10e0\u10d0\u10e1\u10e2\u10d0\u10dc\u10d3\u10d0\u10e0\u10e2\u10e3\u10da\u10d8',
  buildingStatus:K(d,'\u10e8\u10d4\u10dc\u10dd\u10d1\u10d8\u10e1 \u10e1\u10e2\u10d0\u10e2\u10e3\u10e1\u10d8')||buildingStatus||(comment.includes('\u10d0\u10ee\u10d0\u10da\u10d8')?'\u10d0\u10ee\u10d0\u10da\u10d8 \u10d0\u10e8\u10d4\u10dc\u10d4\u10d1\u10e3\u10da\u10d8':undefined),
  phone:K(d,'\u10e2\u10d4\u10da\u10d4\u10e4\u10dd\u10dc\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8','\u10db\u10d4\u10e1\u10d0\u10d9\u10e3\u10d7\u10e0\u10d8\u10e1 \u10dc\u10dd\u10db\u10d4\u10e0\u10d8'), elevator:K(d,'\u10da\u10d8\u10e4\u10e2\u10d8'), parking:K(d,'\u10de\u10d0\u10e0\u10d9\u10d8\u10dc\u10d2\u10d8'), yard:K(d,'\u10d4\u10d6\u10dd')
}; }
const visible = e => !!(e.offsetWidth || e.offsetHeight || e.getClientRects().length);
function text(e) { const labels=e.labels?[...e.labels].map(x=>x.innerText).join(' '):''; const box=e.closest('label,[class*=field],[class*=form],[class*=input],[class*=select]'); return norm([e.name,e.id,e.placeholder,e.getAttribute('aria-label'),labels,box?.innerText?.slice(0,180)].filter(Boolean).join(' ')); }
function ownText(e){const labels=e.labels?[...e.labels].map(x=>x.innerText).join(' '):'';return norm([e.name,e.id,e.placeholder,e.getAttribute('aria-label'),labels].filter(Boolean).join(' '));}
const matches = (e,f) => G[f].some(x => text(e).includes(norm(x)));
function setValue(e,v,commit=true) { const p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:e instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(p,'value')?.set?.call(e,String(v));try{e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:String(v)}));}catch{e.dispatchEvent(new Event('input',{bubbles:true}));}if(commit){e.dispatchEvent(new Event('change',{bubbles:true}));e.dispatchEvent(new Event('blur',{bubbles:true}));} }
async function select(f,v) { if(v==null||v==='')return false; const w=norm(v); const s=[...document.querySelectorAll('select')].find(e=>visible(e)&&matches(e,f)); if(s){const o=[...s.options].find(x=>norm(x.value)===w||norm(x.textContent).includes(w));if(o){setValue(s,o.value);await sleep(150);return true;}} const cs=[...document.querySelectorAll('[role=combobox],button,[aria-haspopup=listbox],[class*=select]')].filter(e=>visible(e)&&matches(e,f)); for(const c of cs){c.click();await sleep(200);const os=[...document.querySelectorAll('[role=option],[role=listbox] li,[class*=option],[class*=menu] li')].filter(visible);const o=os.find(x=>norm(x.textContent)===w)||os.find(x=>norm(x.textContent).includes(w));if(o){o.click();await sleep(200);return true;}} return false; }
function inputCandidates(f,enabledOnly=true){const all=[...document.querySelectorAll('input:not([type=file]):not([type=hidden]):not([type=checkbox]):not([type=radio]),textarea')].filter(x=>visible(x)&&!x.readOnly&&(!enabledOnly||(!x.disabled&&x.getAttribute('aria-disabled')!=='true')));const exact=all.filter(x=>G[f].some(n=>ownText(x)===norm(n)));if(exact.length)return exact;const own=all.filter(x=>G[f].some(n=>ownText(x).includes(norm(n))));if(own.length)return own;return all.filter(x=>matches(x,f));}
function findInput(f){const candidates=inputCandidates(f,true);if(isSsCreatePage()&&f==='description'){return document.querySelector('textarea[placeholder="ჩაწერე აქ..."]')||document.querySelector('textarea')||candidates[0];}if(isSsCreatePage()&&f==='price'){const numeric=[...document.querySelectorAll('input[type=number]')].filter(element=>visible(element)&&!element.disabled&&!element.readOnly);const labeled=numeric.find(element=>text(element).includes(norm('ფასი')));return labeled||numeric[0]||candidates[0];}if(isSsCreatePage()&&f==='street'){const selects=[...document.querySelectorAll('input.select__input[role=combobox],input[role=combobox][id^=react-select-]')].filter(element=>visible(element)&&!element.disabled&&!element.readOnly);const labeled=selects.find(element=>norm(element.closest('[class*=select]')?.parentElement?.innerText).includes(norm('ქუჩა')));return labeled||selects.at(-1)||candidates[0];}if(f==='price'){const pricePerArea=/(price per|price m2|\u10e4\u10d0\u10e1\u10d8 \u10db2)/;return candidates.find(element=>!pricePerArea.test(text(element)))||candidates[0];}return candidates[0];}
function input(f,v){if(v==null||v==='')return false;const e=findInput(f);if(!e)return false;setValue(e,v);return true;}
function inputValueMatches(f,current,wanted){if(String(current??'').trim()===String(wanted??'').trim())return true;if(f==='price'){const actual=Number(String(current??'').replace(/[^\d.-]/g,''));const expected=Number(String(wanted??'').replace(/[^\d.-]/g,''));return Number.isFinite(actual)&&Number.isFinite(expected)&&actual===expected;}return false;}
async function inputVerified(f,v){if(v==null||v==='')return false;for(let attempt=0;attempt<3;attempt++){const element=findInput(f);if(!element)return false;const typed=f==='price'&&element.type==='number'?String(v).replace(/[^\d.-]/g,''):v;if(typed==='')return false;element.focus();setValue(element,typed,false);element.dispatchEvent(new Event('change',{bubbles:true}));element.blur();await sleep(150);const current=findInput(f);if(current&&inputValueMatches(f,current.value,typed))return true;}return false;}
function realClick(element){element.scrollIntoView?.({block:'nearest'});element.focus?.();const down={bubbles:true,cancelable:true,view:window,button:0,buttons:1};const up={...down,buttons:0};if(window.PointerEvent)element.dispatchEvent(new PointerEvent('pointerdown',{...down,pointerId:1,pointerType:'mouse',isPrimary:true}));element.dispatchEvent(new MouseEvent('mousedown',down));if(window.PointerEvent)element.dispatchEvent(new PointerEvent('pointerup',{...up,pointerId:1,pointerType:'mouse',isPrimary:true}));element.dispatchEvent(new MouseEvent('mouseup',up));element.click();}
function clickChoiceOnce(element){element.scrollIntoView?.({block:'nearest'});element.focus?.();element.click();}
function isSsSite(){return /(^|\.)ss\.ge$/i.test(location.hostname);}
function isSsCreatePage(){if(!isSsSite())return false;if(/\/udzravi-qoneba\/create(?:\/|$)/i.test(location.pathname))return true;const dealHeading=norm('\u10d2\u10d0\u10e0\u10d8\u10d2\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8');return [...document.querySelectorAll('label,legend,h1,h2,h3,h4,p,span')].some(element=>visible(element)&&norm(element.textContent)===dealHeading);}
const hasPrimaryChoiceClass=element=>/(^|\s)(?:myhome:)?luk-border-primary-col-(?:blue|green)-100(?=\s|$)/i.test(String(element?.className||''));
function exactVisibleChoice(value){const wanted=norm(value);const candidates=[...document.querySelectorAll('button,label,[role=button],[role=radio],[role=checkbox],div,span,p')].filter(element=>visible(element)&&norm(element.textContent)===wanted);const choice=candidates.sort((a,b)=>{const interactive=element=>element.matches('button,label,[role=button],[role=radio],[role=checkbox]')?0:element.querySelector('input[type=radio],input[type=checkbox]')?1:getComputedStyle(element).cursor==='pointer'?2:3;return interactive(a)-interactive(b)||a.querySelectorAll('*').length-b.querySelectorAll('*').length;})[0];return choice&&isSsCreatePage()?segmentedClickTarget(choice,document.body):choice;}
function exactChoiceSelected(choice){if(!choice)return false;const forId=choice.htmlFor||choice.getAttribute?.('for'),linked=forId?document.getElementById(forId):null;const input=choice.matches('input[type=radio],input[type=checkbox]')?choice:choice.querySelector('input[type=radio],input[type=checkbox]')||(linked?.matches('input[type=radio],input[type=checkbox]')?linked:null);if(input?.checked)return true;if(hasPrimaryChoiceClass(choice)||choice.getAttribute('aria-pressed')==='true'||choice.getAttribute('aria-checked')==='true'||choice.getAttribute('aria-selected')==='true'||choice.getAttribute('data-selected')==='true'||/^(checked|selected|active|on)$/i.test(choice.getAttribute('data-state')||'')||/(^|\s)(active|selected|checked)(\s|$)/i.test(String(choice.className)))return true;const iconMarkup=[...choice.querySelectorAll('svg,use,[class*=icon]')].map(icon=>[icon.getAttribute('aria-label'),icon.getAttribute('title'),icon.getAttribute('href'),icon.getAttribute('xlink:href'),icon.className?.baseVal||icon.className].filter(Boolean).join(' ')).join(' ');return /(^|\W)(check|checked|done)(\W|$)/i.test(iconMarkup);}
async function setExactChoice(value,selected=true){const key=norm(value),ssMode=isSsCreatePage();if(ssMode&&ssAppliedExactChoices.get(key)===selected)return true;for(let attempt=0;attempt<4;attempt++){const choice=exactVisibleChoice(value);if(!choice){await sleep(150);continue;}if(exactChoiceSelected(choice)===selected){if(ssMode)ssAppliedExactChoices.set(key,selected);return true;}if(ssMode)clickChoiceOnce(choice);else realClick(choice);await sleep(350);if(ssMode){ssAppliedExactChoices.set(key,selected);return true;}const current=exactVisibleChoice(value);if(current&&exactChoiceSelected(current)===selected)return true;}const current=exactVisibleChoice(value);return !!current&&exactChoiceSelected(current)===selected;}
const CHOICE_SELECTOR = 'label,button,input[type=radio],[role=radio],[aria-pressed],[aria-checked],[aria-selected]';
function choiceControl(element){if(element.matches('input[type=radio],input[type=checkbox]'))return element;if(element.matches('label'))return element.control||element.querySelector('input[type=radio],input[type=checkbox]');return element.querySelector?.('input[type=radio],input[type=checkbox]')||null;}
function choiceRawText(element,control){if(element.matches('input[type=radio],input[type=checkbox]')){const labels=control?.labels?[...control.labels].filter(visible).map(label=>label.innerText||label.textContent):[];return labels.join(' ')||element.getAttribute('aria-label')||element.value||'';}return element.innerText||element.textContent||element.getAttribute('aria-label')||'';}
function semanticChoiceVisible(element){if(!visible(element)||element.closest('[aria-hidden=true],[hidden],[inert]'))return false;const style=getComputedStyle(element),rect=element.getBoundingClientRect(),viewportWidth=document.documentElement.clientWidth||window.innerWidth;return style.display!=='none'&&style.visibility!=='hidden'&&style.opacity!=='0'&&rect.right>0&&rect.left<viewportWidth;}
function semanticChoiceEntries(root=document){const result=[],seen=new Set();for(const original of root.querySelectorAll(CHOICE_SELECTOR)){let element=original;if(element.matches('input[type=radio]')){const label=[...(element.labels||[])].find(semanticChoiceVisible);if(label)element=label;}const owner=element.closest?.('label,button,[role=radio]');if(owner&&owner!==element&&semanticChoiceVisible(owner))element=owner;if(!semanticChoiceVisible(element))continue;const control=choiceControl(element);const key=control||element;if(seen.has(key))continue;const raw=choiceRawText(element,control).trim(),value=norm(raw);if(!value)continue;seen.add(key);result.push({element,control,raw,value});}return result;}
function semanticChoiceSelected(choice){if(!choice)return false;if(choice.control?.checked)return true;for(const element of [choice.element,choice.control].filter(Boolean)){if(hasPrimaryChoiceClass(element)||element.getAttribute('aria-checked')==='true'||element.getAttribute('aria-pressed')==='true'||element.getAttribute('aria-selected')==='true'||element.getAttribute('data-selected')==='true'||/^(checked|selected|active|on)$/i.test(element.getAttribute('data-state')||'')||/(^|\s)(active|selected|checked)(\s|$)/i.test(String(element.className)))return true;}return false;}
function viewportDistance(element){const rect=element.getBoundingClientRect(),height=window.innerHeight||document.documentElement.clientHeight;if(rect.bottom>=0&&rect.top<=height)return 0;return rect.top>height?rect.top-height:-rect.bottom;}
function semanticChoicePeers(anchor,choices){if(!anchor)return [];const control=anchor.control;if(control?.type==='radio'&&control.name){return choices.filter(choice=>choice.control?.type==='radio'&&choice.control.name===control.name&&choice.control.form===control.form);}const group=anchor.element.closest?.('[role=radiogroup],fieldset');if(group){const peers=choices.filter(choice=>group.contains(choice.element));if(peers.length>=2)return peers;}return choices;}
function semanticChoiceGroupState(desired,choices,wanted){const peers=semanticChoicePeers(desired,choices),selected=semanticChoiceSelected(desired),conflicting=peers.some(choice=>choice.value!==wanted&&semanticChoiceSelected(choice));return {desired,peers,selected,conflicting,confirmed:selected&&!conflicting};}
function ownNormalizedText(element){return norm([...element.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).map(node=>node.textContent).join(' '));}
function knownTransactionChoices(root){const known=new Set(TRANSACTION_VALUES.map(norm));return semanticChoiceEntries(root).filter(choice=>known.has(choice.value));}
function transactionHeadings(){const aliases=G.transaction.map(norm);return [...document.querySelectorAll('label,legend,h1,h2,h3,h4,h5,p,span,div')].filter(element=>semanticChoiceVisible(element)&&(aliases.includes(ownNormalizedText(element))||aliases.includes(norm(element.textContent)))).sort((a,b)=>viewportDistance(a)-viewportDistance(b)||a.querySelectorAll('*').length-b.querySelectorAll('*').length);}
function findTransactionScope(){for(const heading of transactionHeadings()){for(let root=heading.parentElement,depth=0;root&&root!==document.body&&depth<8;root=root.parentElement,depth++){const choices=knownTransactionChoices(root);if(new Set(choices.map(choice=>choice.value)).size>=2)return root;}}const roots=[];for(const choice of knownTransactionChoices(document)){for(let root=choice.element.parentElement,depth=0;root&&root!==document.body&&depth<8;root=root.parentElement,depth++){const choices=knownTransactionChoices(root);if(new Set(choices.map(candidate=>candidate.value)).size>=2){roots.push(root);break;}}}return [...new Set(roots)].length===1?roots[0]:null;}
function transactionDropdownControls(){const selector='select,[role=combobox],[aria-haspopup=listbox]',controls=[...document.querySelectorAll(selector)].filter(semanticChoiceVisible),matched=controls.filter(control=>matches(control,'transaction'));if(matched.length)return matched;for(const heading of transactionHeadings()){for(let root=heading.parentElement,depth=0;root&&root!==document.body&&depth<7;root=root.parentElement,depth++){const scoped=[...root.querySelectorAll(selector)].filter(semanticChoiceVisible);if(scoped.length)return scoped;}}return [];}
function dropdownDisplayedValues(control){return [control.value,control.getAttribute('aria-valuetext'),control.innerText,control.textContent,control.querySelector('input')?.value,...[...control.querySelectorAll('*')].map(ownNormalizedText)].filter(Boolean).map(norm);}
function transactionDropdownSnapshot(value){const canonical=canonicalTransaction(value),wanted=norm(canonical||value);for(const control of transactionDropdownControls()){if(control instanceof HTMLSelectElement){const options=[...control.options],desired=canonical?options.find(option=>norm(option.textContent)===wanted||norm(option.value)===wanted):undefined,selected=options[control.selectedIndex];return {control,desired,confirmed:!!desired&&!!selected&&(norm(selected.textContent)===wanted||norm(selected.value)===wanted),available:[...new Set(options.map(option=>option.textContent.trim()).filter(Boolean))]};}const available=[...new Set([control.innerText,control.textContent].filter(Boolean).map(value=>value.trim()))],confirmed=!!canonical&&dropdownDisplayedValues(control).includes(wanted);return {control,desired:null,confirmed,available};}return {control:null,desired:null,confirmed:false,available:[]};}
async function selectTransactionDropdown(value){const canonical=canonicalTransaction(value);if(!canonical)return false;for(let attempt=0;attempt<3;attempt++){let state=transactionDropdownSnapshot(canonical);if(state.confirmed)return true;if(!state.control)return false;if(state.control instanceof HTMLSelectElement){if(!state.desired)return false;setValue(state.control,state.desired.value);if(await waitUntil(()=>transactionDropdownSnapshot(canonical).confirmed,1800))return true;continue;}realClick(state.control);await sleep(250);const wanted=norm(canonical),options=[...document.querySelectorAll('[role=option],[role=listbox] li')].filter(semanticChoiceVisible),available=[...new Set(options.map(option=>(option.innerText||option.textContent||'').trim()).filter(Boolean))];if(available.length)listingLog('available transaction options:',available);const option=options.find(candidate=>norm(candidate.innerText||candidate.textContent)===wanted);if(option){realClick(option);if(await waitUntil(()=>transactionDropdownSnapshot(canonical).confirmed||transactionSnapshot(canonical,true).confirmed,2000))return true;}await sleep(200);}return false;}
function transactionSnapshot(value,skipDropdown=false){const canonical=canonicalTransaction(value),wanted=norm(canonical||value),scope=findTransactionScope(),globalChoices=knownTransactionChoices(document);const choices=scope?knownTransactionChoices(scope):[];const desiredChoices=canonical?choices.filter(choice=>choice.value===wanted):[],groups=desiredChoices.map(choice=>semanticChoiceGroupState(choice,choices,wanted)),group=groups.find(state=>state.confirmed)||groups.find(state=>state.selected)||groups[0],desired=group?.desired,ssRentalCommitted=isSsCreatePage()&&wanted===norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0')&&ssCreateHeadingVisible('\u10d2\u10d0\u10e5\u10d8\u10e0\u10d0\u10d5\u10d4\u10d1\u10d8\u10e1 \u10de\u10e0\u10d8\u10dd\u10d3\u10d8'),selected=!!group?.selected||ssRentalCommitted,conflicting=!!group?.conflicting&&!ssRentalCommitted;const dropdown=skipDropdown?{confirmed:false,available:[]} : transactionDropdownSnapshot(canonical||value);return {canonical,wanted,scope,choices,desired,selected:selected||dropdown.confirmed,conflicting,confirmed:ssRentalCommitted||!!group?.confirmed||(!desiredChoices.length&&dropdown.confirmed),available:[...new Set([...globalChoices.map(choice=>choice.raw.trim()),...(dropdown.available||[])])]};}
async function transactionRemainsSelected(value,stableMs=500,timeout=1800){const end=Date.now()+timeout;let stableSince=0;while(Date.now()<end){const state=transactionSnapshot(value);if(state.confirmed){if(!stableSince)stableSince=Date.now();if(Date.now()-stableSince>=stableMs)return true;}else stableSince=0;await sleep(80);}return false;}
async function bridgeChoice(kind,value){const root=document.documentElement,requestId=`choice-${Date.now()}-${Math.random()}`;root.dataset.nikasChoiceRequest=requestId;root.dataset.nikasChoiceKind=kind;root.dataset.nikasChoiceValue=String(value);root.dataset.nikasChoiceStatus='working';root.dataset.nikasChoiceAvailable='[]';root.dispatchEvent(new Event('nikas:choice'));const done=await waitUntil(()=>root.dataset.nikasChoiceResponse===requestId&&root.dataset.nikasChoiceStatus!=='working',7000);let available=[];try{available=JSON.parse(root.dataset.nikasChoiceAvailable||'[]');}catch{}return {ok:!!done&&root.dataset.nikasChoiceStatus==='ok',reason:done?(root.dataset.nikasChoiceReason||'confirmation-failed'):'main-world-bridge-timeout',available};}
async function selectTransactionChoice(value){if(value==null||String(value).trim()==='')return true;const canonical=canonicalTransaction(value);listingLog('transaction from JSON:',value);listingLog('desired transaction:',canonical||norm(value));if(!canonical){const state=transactionSnapshot(value);listingLog('found transaction option:',false);listingLog('available transaction options:',state.available);listingLog('transaction selected:',false);return false;}if(isSsCreatePage()&&norm(canonical)===norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0')){const selected=await selectSsCreateCard('აირჩიეთ გარიგების ტიპი',canonical,'\u10d2\u10d0\u10e5\u10d8\u10e0\u10d0\u10d5\u10d4\u10d1\u10d8\u10e1 \u10de\u10e0\u10d8\u10dd\u10d3\u10d8');if(selected&&await transactionRemainsSelected(canonical,400,1800))return listingLog('SS transaction card selected:',true),true;}for(let attempt=0;attempt<4;attempt++){let state=transactionSnapshot(canonical);listingLog('found transaction option:',!!state.desired||!!transactionDropdownSnapshot(canonical).control);if(state.confirmed&&await transactionRemainsSelected(canonical))return listingLog('transaction selected:',true),true;if(!state.desired&&await selectTransactionDropdown(canonical)&&await transactionRemainsSelected(canonical))return listingLog('transaction selected:',true),true;const bridged=await bridgeChoice('transaction',canonical);if(bridged.available.length)listingLog('available transaction options:',bridged.available);if(bridged.ok&&await transactionRemainsSelected(canonical))return listingLog('transaction selected:',true),true;state=transactionSnapshot(canonical);if(state.desired){realClick(state.desired.element);if(await transactionRemainsSelected(canonical,500,2000))return listingLog('transaction selected:',true),true;}await sleep(250);}const state=transactionSnapshot(canonical);listingLog('available transaction options:',state.available);listingLog('transaction selected:',false);return false;}
function exactSemanticChoiceSnapshot(value){const wanted=norm(value),candidates=semanticChoiceEntries(document).filter(choice=>choice.value===wanted);for(const candidate of candidates){for(let root=candidate.element.parentElement,depth=0;root&&root!==document.body&&depth<7;root=root.parentElement,depth++){const peers=semanticChoiceEntries(root).filter(choice=>candidate.control?(choice.control?.type===candidate.control.type&&(!candidate.control.name||choice.control.name===candidate.control.name)):choice.element.matches('button,[role=radio],[aria-pressed],[aria-checked],[aria-selected]'));if(peers.length<2)continue;const desiredChoices=peers.filter(choice=>choice.value===wanted),desired=desiredChoices.find(semanticChoiceSelected)||desiredChoices.find(choice=>choice.control===candidate.control||choice.element===candidate.element)||desiredChoices[0];const selected=desiredChoices.some(semanticChoiceSelected),conflicting=peers.some(choice=>choice.value!==wanted&&semanticChoiceSelected(choice));return {desired,peers,selected,conflicting,confirmed:selected&&!conflicting,available:[...new Set(peers.map(choice=>choice.raw.trim()))]};}return {desired:candidate,peers:[candidate],selected:semanticChoiceSelected(candidate),conflicting:false,confirmed:semanticChoiceSelected(candidate),available:[candidate.raw.trim()]};}return {desired:null,peers:[],selected:false,conflicting:false,confirmed:false,available:[]};}
async function exactSemanticChoiceRemainsSelected(value,stableMs=500,timeout=1800){const end=Date.now()+timeout;let stableSince=0;while(Date.now()<end){if(exactSemanticChoiceSnapshot(value).confirmed){if(!stableSince)stableSince=Date.now();if(Date.now()-stableSince>=stableMs)return true;}else stableSince=0;await sleep(80);}return false;}
async function selectExactSemanticChoice(value){if(exactSemanticChoiceSnapshot(value).confirmed&&await exactSemanticChoiceRemainsSelected(value))return true;for(let attempt=0;attempt<4;attempt++){const bridged=await bridgeChoice('exact',value);if(bridged.ok&&await exactSemanticChoiceRemainsSelected(value))return true;const current=exactSemanticChoiceSnapshot(value);if(current.desired){realClick(current.desired.element);if(await exactSemanticChoiceRemainsSelected(value,500,2000))return true;}await sleep(200);}return false;}
function ssRentalPeriodScope(){const aliases=SS_RENTAL_PERIOD_ALIASES.map(norm),known=new Set(SS_RENTAL_PERIOD_VALUES.map(norm));const headings=[...document.querySelectorAll('label,legend,h1,h2,h3,h4,h5,p,span,div')].filter(element=>semanticChoiceVisible(element)&&(aliases.includes(ownNormalizedText(element))||aliases.includes(norm(element.textContent)))).sort((a,b)=>viewportDistance(a)-viewportDistance(b)||a.querySelectorAll('*').length-b.querySelectorAll('*').length);for(const heading of headings){for(let root=heading.parentElement,depth=0;root&&root!==document.body&&depth<7;root=root.parentElement,depth++){const choices=semanticChoiceEntries(root).filter(choice=>known.has(choice.value));if(new Set(choices.map(choice=>choice.value)).size>=2)return root;}}return null;}
function ssRentalPeriodSnapshot(value=SS_DEFAULT_RENTAL_PERIOD){const wanted=norm(value),known=new Set(SS_RENTAL_PERIOD_VALUES.map(norm)),scope=ssRentalPeriodScope(),allChoices=semanticChoiceEntries(scope||document).filter(choice=>known.has(choice.value)),choices=scope?allChoices:(new Set(allChoices.map(choice=>choice.value)).size>=2?allChoices:[]),desiredChoices=choices.filter(choice=>choice.value===wanted),groups=desiredChoices.map(choice=>semanticChoiceGroupState(choice,choices,wanted)),group=groups.find(state=>state.confirmed)||groups.find(state=>state.selected)||groups[0];return {desired:group?.desired,choices,selected:!!group?.selected,conflicting:!!group?.conflicting,confirmed:!!group?.confirmed,available:[...new Set(choices.map(choice=>choice.raw.trim()))]};}
async function selectSsRentalPeriod(value=SS_DEFAULT_RENTAL_PERIOD){let state=null;const mounted=await waitUntil(()=>{state=ssRentalPeriodSnapshot(value);return !!state.desired;},5000);listingLog('found rental-period option:',mounted);if(!mounted)return listingLog('rental period selected:',false),false;if(state.confirmed)return listingLog('rental period selected:',true),true;for(let attempt=0;attempt<5;attempt++){state=ssRentalPeriodSnapshot(value);if(state.confirmed)return listingLog('rental period selected:',true),true;if(state.desired){listingLog('pressing visible default rental period:',value);realClick(state.desired.element);if(await waitUntil(()=>ssRentalPeriodSnapshot(value).confirmed,900))return listingLog('rental period selected:',true),true;state=ssRentalPeriodSnapshot(value);if(state.desired?.control&&!state.desired.control.disabled){listingLog('pressing linked rental-period radio:',value);state.desired.control.click();if(await waitUntil(()=>ssRentalPeriodSnapshot(value).confirmed,1200))return listingLog('rental period selected:',true),true;}}const bridged=await bridgeChoice('exact',value);state=ssRentalPeriodSnapshot(value);if(bridged.ok&&state.confirmed)return listingLog('rental period selected:',true),true;await sleep(200);}state=ssRentalPeriodSnapshot(value);listingLog('available rental-period options:',state.available);listingLog('rental period selected:',false);return false;}
function rentalTypeSnapshot(value=DEFAULT_RENTAL_TYPE){const wanted=norm(value),candidates=semanticChoiceEntries(document).filter(choice=>choice.value===wanted).sort((a,b)=>viewportDistance(a.element)-viewportDistance(b.element));if(!candidates.length)return {desired:null,selected:false,conflicting:false,confirmed:false,available:[]};const desired=candidates[0];let peers=semanticChoicePeers(desired,semanticChoiceEntries(document));if(!desired.control?.name&&!desired.element.closest?.('[role=radiogroup],fieldset')){for(let root=desired.element.parentElement,depth=0;root&&root!==document.body&&depth<7;root=root.parentElement,depth++){const scoped=semanticChoiceEntries(root);if(scoped.length>=2){peers=scoped;break;}}}const state=semanticChoiceGroupState(desired,peers,wanted);return {...state,available:[...new Set(peers.map(choice=>choice.raw.trim()))]};}
async function selectDefaultRentalType(value=DEFAULT_RENTAL_TYPE){let state=null;const mounted=await waitUntil(()=>{state=rentalTypeSnapshot(value);return !!state.desired;},5000);listingLog('found rental-type option:',mounted);if(!mounted)return listingLog('rental type selected:',false),false;if(state.confirmed)return listingLog('rental type selected:',true),true;for(let attempt=0;attempt<5;attempt++){state=rentalTypeSnapshot(value);if(state.confirmed)return listingLog('rental type selected:',true),true;if(state.desired){listingLog('pressing visible default rental type:',value);realClick(state.desired.element);if(await waitUntil(()=>rentalTypeSnapshot(value).confirmed,900))return listingLog('rental type selected:',true),true;state=rentalTypeSnapshot(value);if(state.desired?.control&&!state.desired.control.disabled){listingLog('pressing linked rental-type radio:',value);state.desired.control.click();if(await waitUntil(()=>rentalTypeSnapshot(value).confirmed,1200))return listingLog('rental type selected:',true),true;}}const bridged=await bridgeChoice('exact',value);state=rentalTypeSnapshot(value);if(bridged.ok&&state.confirmed)return listingLog('rental type selected:',true),true;await sleep(200);}state=rentalTypeSnapshot(value);listingLog('available rental-type options:',state.available);listingLog('rental type selected:',false);return false;}
async function stabilizeRentalChoices(transaction,stableDuration=1200){lastDealSelectionReason='';if(transaction==null||String(transaction).trim()==='')return true;const canonical=canonicalTransaction(transaction);if(!canonical){lastDealSelectionReason='transaction';return false;}const rental=norm(canonical)===norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0'),end=Date.now()+24000;let stableSince=0;while(Date.now()<end){if(!transactionSnapshot(canonical).confirmed){stableSince=0;if(!await selectTransactionChoice(canonical)){await sleep(250);continue;}}if(rental&&!ssRentalPeriodSnapshot().confirmed){stableSince=0;if(!await selectSsRentalPeriod()){await sleep(250);continue;}await sleep(250);}if(rental&&!rentalTypeSnapshot().confirmed){stableSince=0;if(!await selectDefaultRentalType()){await sleep(250);continue;}await sleep(250);}const transactionReady=transactionSnapshot(canonical).confirmed,periodReady=!rental||ssRentalPeriodSnapshot().confirmed,typeReady=!rental||rentalTypeSnapshot().confirmed;if(transactionReady&&periodReady&&typeReady){if(!stableSince)stableSince=Date.now();if(Date.now()-stableSince>=stableDuration)return true;}else stableSince=0;await sleep(120);}const transactionReady=transactionSnapshot(canonical).confirmed,periodReady=!rental||ssRentalPeriodSnapshot().confirmed,typeReady=!rental||rentalTypeSnapshot().confirmed;lastDealSelectionReason=!transactionReady?'transaction':!periodReady?'rental-period':!typeReady?'rental-type':'transaction';if(!periodReady)listingLog('available rental-period options:',ssRentalPeriodSnapshot().available);if(!typeReady)listingLog('available rental-type options:',rentalTypeSnapshot().available);return false;}
function createImageUiWatcher(){let lastChange=Date.now(),mutationCount=0;const observer=new MutationObserver(records=>{if(records.some(record=>record.type==='childList'||record.attributeName==='src')){lastChange=Date.now();mutationCount++;}});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['src']});return {async settle(imageCount){const started=Date.now(),end=started+20000;try{while(Date.now()<end){if(Date.now()-started>=2000&&Date.now()-lastChange>=2500){listingLog('image UI settled:',{imageCount,mutationCount});return true;}await sleep(120);}listingLog('image UI settle timeout:',{imageCount,mutationCount});return false;}finally{observer.disconnect();}}};}
async function stabilizeDealAfterImages(data){const transaction=values(data).transaction;if(transaction==null||String(transaction).trim()==='')return true;const selected=await stabilizeRentalChoices(transaction,3500);listingLog('post-image transaction selected:',selected);if(!selected)listingLog('available transaction options:',transactionSnapshot(transaction).available);return selected;}
function maintainSsRentalDefault(transaction,duration=20000){const canonical=canonicalTransaction(transaction);if(norm(canonical)!==norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0'))return;const end=Date.now()+duration;(async()=>{while(Date.now()<end){if(!transactionSnapshot(canonical).confirmed)await selectTransactionChoice(canonical);if(transactionSnapshot(canonical).confirmed&&!ssRentalPeriodSnapshot().confirmed)await selectSsRentalPeriod();if(transactionSnapshot(canonical).confirmed&&ssRentalPeriodSnapshot().confirmed&&!rentalTypeSnapshot().confirmed)await selectDefaultRentalType();await sleep(500);}})().catch(error=>listingLog('rental default guard failed:',error.message));}
function ssCreateHeadingVisible(text){const wanted=norm(text);return [...document.querySelectorAll('h1,h2,h3,h4,h5,label,p,span,div')].some(element=>semanticChoiceVisible(element)&&norm(element.textContent)===wanted);}
function ssCreateCard(headingText,value){const headingWanted=norm(headingText),valueWanted=norm(value),headings=[...document.querySelectorAll('h1,h2,h3,h4,h5,label,p,span,div')].filter(element=>semanticChoiceVisible(element)&&norm(element.textContent)===headingWanted).sort((a,b)=>viewportDistance(a)-viewportDistance(b)||a.querySelectorAll('*').length-b.querySelectorAll('*').length);for(const heading of headings){for(let root=heading.parentElement,depth=0;root&&root!==document.body&&depth<6;root=root.parentElement,depth++){const nodes=[...root.querySelectorAll('button,label,[role=radio],[role=button],div,span,p')].filter(element=>semanticChoiceVisible(element)&&norm(element.textContent)===valueWanted);for(const node of nodes.sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)){for(let target=node,up=0;target&&target!==root&&up<5;target=target.parentElement,up++){if(target.closest('a[href]'))break;const rect=target.getBoundingClientRect(),cardShape=target.matches('div')&&rect.width>=80&&rect.height>=40,ownPointer=target.matches('button,label,[role=radio],[role=button]')||[...target.classList||[]].some(name=>name.includes('cursor-pointer'))||cardShape;if(ownPointer&&getComputedStyle(target).pointerEvents!=='none')return target;}}}}return null;}
async function selectSsCreateCard(headingText,value,_nextHeading){for(let attempt=0;attempt<5;attempt++){const card=ssCreateCard(headingText,value);if(!card){await sleep(250);continue;}listingLog('pressing SS card once:',value);clickChoiceOnce(card);await sleep(450);return true;}return false;}
function ssTransactionCardsPresent(){return isSsCreatePage()&&ssCreateHeadingVisible('\u10d0\u10d8\u10e0\u10e9\u10d8\u10d4\u10d7 \u10d2\u10d0\u10e0\u10d8\u10d2\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8');}
function ssRentalTransactionCardConfirmed(transaction){return ssTransactionCardsPresent()&&norm(ssTransactionCardValue)===norm(transaction);}
async function ensureTransactionChoice(transaction){if(ssTransactionCardsPresent()){if(ssRentalTransactionCardConfirmed(transaction))return true;const selected=await selectSsCreateCard('\u10d0\u10d8\u10e0\u10e9\u10d8\u10d4\u10d7 \u10d2\u10d0\u10e0\u10d8\u10d2\u10d4\u10d1\u10d8\u10e1 \u10e2\u10d8\u10de\u10d8',transaction);if(selected)ssTransactionCardValue=String(transaction);return selected;}return selectTransactionChoice(transaction);}
async function stabilizeRentalChoices(transaction,stableDuration=1200){lastDealSelectionReason='';if(transaction==null||String(transaction).trim()==='')return true;const canonical=canonicalTransaction(transaction);if(!canonical){lastDealSelectionReason='transaction';return false;}const rental=norm(canonical)===norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0'),myHomeRentalDefaults=rental&&!ssTransactionCardsPresent(),end=Date.now()+24000;let stableSince=0;while(Date.now()<end){const transactionReady=transactionSnapshot(canonical).confirmed||ssRentalTransactionCardConfirmed(canonical);if(!transactionReady){stableSince=0;if(!await ensureTransactionChoice(canonical)){await sleep(250);continue;}}if(myHomeRentalDefaults&&!ssRentalPeriodSnapshot().confirmed){stableSince=0;if(!await selectSsRentalPeriod()){await sleep(250);continue;}await sleep(250);}if(myHomeRentalDefaults&&!rentalTypeSnapshot().confirmed){stableSince=0;if(!await selectDefaultRentalType()){await sleep(250);continue;}await sleep(250);}const ready=(transactionSnapshot(canonical).confirmed||ssRentalTransactionCardConfirmed(canonical))&&(!myHomeRentalDefaults||ssRentalPeriodSnapshot().confirmed)&&(!myHomeRentalDefaults||rentalTypeSnapshot().confirmed);if(ready){if(!stableSince)stableSince=Date.now();if(Date.now()-stableSince>=stableDuration)return true;}else stableSince=0;await sleep(120);}const transactionReady=transactionSnapshot(canonical).confirmed||ssRentalTransactionCardConfirmed(canonical),periodReady=!myHomeRentalDefaults||ssRentalPeriodSnapshot().confirmed,typeReady=!myHomeRentalDefaults||rentalTypeSnapshot().confirmed;lastDealSelectionReason=!transactionReady?'transaction':!periodReady?'rental-period':!typeReady?'rental-type':'transaction';return false;}
function maintainSsRentalDefault(transaction,duration=20000){if(ssTransactionCardsPresent())return;const canonical=canonicalTransaction(transaction);if(norm(canonical)!==norm('\u10e5\u10d8\u10e0\u10d0\u10d5\u10d3\u10d4\u10d1\u10d0'))return;const end=Date.now()+duration;(async()=>{while(Date.now()<end){if(!transactionSnapshot(canonical).confirmed)await selectTransactionChoice(canonical);if(transactionSnapshot(canonical).confirmed&&!ssRentalPeriodSnapshot().confirmed)await selectSsRentalPeriod();if(transactionSnapshot(canonical).confirmed&&ssRentalPeriodSnapshot().confirmed&&!rentalTypeSnapshot().confirmed)await selectDefaultRentalType();await sleep(500);}})().catch(error=>listingLog('rental default guard failed:',error.message));}
async function applySsCreateDefaults(){if(!isSsCreatePage())return 0;let count=0;if(await selectSsCreateCard('აირჩიე კატეგორია','უძრავი ქონება','აირჩიეთ უძრავი ქონების ტიპი'))count++;await sleep(250);if(await selectSsCreateCard('აირჩიეთ უძრავი ქონების ტიპი','ბინა','აირჩიეთ გარიგების ტიპი'))count++;return count;}
function ssAdditionalInfoSettings(source={}){const formValues=source&&Object.prototype.hasOwnProperty.call(source,'floor')?source:values(source),floor=Number(formValues.floor),total=Number(formValues.totalFloors);return {...SS_CREATE_DEFAULTS.details,'ბოლო სართული':Number.isFinite(floor)&&Number.isFinite(total)&&floor===total};}
function ssAdditionalInfoReady(settings){return Object.keys(settings).some(value=>!!exactVisibleChoice(value));}
function exactSsChoiceConfirmed(value,selected=true){const choice=exactVisibleChoice(value);return !!choice&&(exactChoiceSelected(choice)===selected||ssAppliedExactChoices.get(norm(value))===selected);}
function ssAdditionalInfoConfirmed(settings){return Object.entries(settings).filter(([value])=>!!exactVisibleChoice(value)).every(([value,selected])=>exactSsChoiceConfirmed(value,selected));}
async function applySsAdditionalInfoDefaults(source={}){if(!isSsCreatePage())return true;const settings=ssAdditionalInfoSettings(source),mounted=await waitUntil(()=>ssAdditionalInfoReady(settings)||!!exactVisibleChoice(DEFAULT_PROJECT_TYPE),7000);listingLog('SS additional information mounted:',mounted);if(!mounted){listingLog('SS additional information not mounted; continuing with remaining fields');return true;}for(let pass=0;pass<3;pass++){await setExactChoice(DEFAULT_PROJECT_TYPE,true);for(const [value,selected] of Object.entries(settings)){if(exactVisibleChoice(value))await setExactChoice(value,selected);}if(exactSsChoiceConfirmed(DEFAULT_PROJECT_TYPE,true)&&ssAdditionalInfoConfirmed(settings))return listingLog('SS additional information and project selected:',true),true;await sleep(300);}const unconfirmed=[DEFAULT_PROJECT_TYPE,...Object.keys(settings)].filter(value=>exactVisibleChoice(value)&&!exactSsChoiceConfirmed(value,value===DEFAULT_PROJECT_TYPE?true:settings[value]));listingLog('SS unconfirmed visible choices (continuing):',unconfirmed);return true;}
function maintainSsAdditionalInfoDefaults(source={},duration=20000){if(!isSsCreatePage())return;const settings=ssAdditionalInfoSettings(source),end=Date.now()+duration;(async()=>{while(Date.now()<end){if(!ssAdditionalInfoConfirmed(settings))await applySsAdditionalInfoDefaults(source);await sleep(500);}})().catch(error=>listingLog('SS additional-information guard failed:',error.message));}
async function selectPromptOption(prompt,value){const promptText=norm(prompt),wanted=norm(value);for(let attempt=0;attempt<4;attempt++){const label=[...document.querySelectorAll('span,label,p,div')].filter(element=>visible(element)&&norm(element.textContent)===promptText).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!label){await sleep(150);continue;}let trigger=label;while(trigger.parentElement&&trigger!==document.body){if(trigger.matches('[role=combobox],button,[aria-haspopup=listbox]')||getComputedStyle(trigger).cursor==='pointer')break;trigger=trigger.parentElement;}realClick(trigger);let option=null;await waitUntil(()=>{option=[...document.querySelectorAll('[role=option],li')].filter(visible).find(element=>norm(element.textContent)===wanted);return !!option;},2000);if(option){realClick(option);await sleep(250);return true;}}return false;}
const waitUntil=async(test,timeout=3000)=>{const end=Date.now()+timeout;while(Date.now()<end){if(test())return true;await sleep(60);}return false;};
function projectTypeTrigger(){const prompts=[norm('აირჩიეთ პროექტის ტიპი'),norm('პროექტის ტიპი')],nodes=[...document.querySelectorAll('span,label,p,div')].filter(element=>semanticChoiceVisible(element)&&prompts.includes(norm(element.textContent))).sort((a,b)=>prompts.indexOf(norm(a.textContent))-prompts.indexOf(norm(b.textContent))||viewportDistance(a)-viewportDistance(b)||a.querySelectorAll('*').length-b.querySelectorAll('*').length);for(const node of nodes){for(let trigger=node,depth=0;trigger&&trigger!==document.body&&depth<6;trigger=trigger.parentElement,depth++){const ownPointer=trigger.classList?.contains('luk-cursor-pointer')||trigger.matches('[role=combobox],button,[aria-haspopup=listbox]')||!!trigger.querySelector?.(':scope > img[alt="arrow"]');if(ownPointer&&getComputedStyle(trigger).pointerEvents!=='none')return trigger;}}return null;}
function projectTypeSnapshot(value=DEFAULT_PROJECT_TYPE){const wanted=norm(value),selects=[...document.querySelectorAll('select')].filter(element=>semanticChoiceVisible(element)&&matches(element,'project'));for(const control of selects){const selected=control.options[control.selectedIndex],confirmed=!!selected&&(norm(selected.textContent)===wanted||norm(selected.value)===wanted);return {control,confirmed,available:[...control.options].map(option=>option.textContent.trim()).filter(Boolean)};}const control=projectTypeTrigger(),displayed=control?[control.innerText,control.textContent,...[...control.querySelectorAll('*')].map(element=>element.textContent)].filter(Boolean).map(norm):[],promptValues=new Set([norm('აირჩიეთ პროექტის ტიპი'),norm('პროექტის ტიპი')]),valueNodes=[...document.querySelectorAll('span,p,div')].filter(element=>semanticChoiceVisible(element)&&norm(element.textContent)===wanted),pairedValue=valueNodes.some(node=>{for(let root=node.parentElement,depth=0;root&&root!==document.body&&depth<5;root=root.parentElement,depth++){if([...root.querySelectorAll('span,label,p,div')].some(element=>promptValues.has(norm(element.textContent))))return true;}return false;});return {control,confirmed:displayed.includes(wanted)||pairedValue,available:[]};}
async function selectDefaultProjectType(value=DEFAULT_PROJECT_TYPE){const wanted=norm(value),mounted=await waitUntil(()=>!!projectTypeSnapshot(value).control,5000);listingLog('found project-type dropdown:',mounted);if(!mounted)return listingLog('project type selected:',false),false;for(let attempt=0;attempt<5;attempt++){let state=projectTypeSnapshot(value);if(state.confirmed)return listingLog('project type selected:',true),true;if(state.control instanceof HTMLSelectElement){const option=[...state.control.options].find(candidate=>norm(candidate.textContent)===wanted||norm(candidate.value)===wanted);if(option){setValue(state.control,option.value);if(await waitUntil(()=>projectTypeSnapshot(value).confirmed,1200))return listingLog('project type selected:',true),true;}}else if(state.control){listingLog('opening project-type dropdown');realClick(state.control);let option=null;await waitUntil(()=>{option=[...document.querySelectorAll('[role=option],li')].filter(semanticChoiceVisible).find(element=>norm(element.textContent)===wanted);return !!option;},2200);if(option){listingLog('pressing default project type:',value);realClick(option);if(await waitUntil(()=>projectTypeSnapshot(value).confirmed,1800))return listingLog('project type selected:',true),true;}}await sleep(200);}const state=projectTypeSnapshot(value);listingLog('available project-type options:',state.available);listingLog('project type selected:',false);return false;}
function maintainDefaultProjectType(duration=20000){const end=Date.now()+duration;(async()=>{while(Date.now()<end){if(!projectTypeSnapshot().confirmed)await selectDefaultProjectType();await sleep(500);}})().catch(error=>listingLog('project default guard failed:',error.message));}
const directText=element=>norm([...element.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).map(node=>node.textContent).join(' '));
function hasDirectText(root,wanted){if(directText(root)===wanted)return true;return [...root.querySelectorAll('*')].some(node=>visible(node)&&directText(node)===wanted);}
function locationRow(value){const primary=norm(value),subtitle=norm('\u10e5\u10d0\u10da\u10d0\u10e5\u10d8');const primaryNodes=[...document.querySelectorAll('[role=option] *,li *,[class*=option] *,[class*=suggest] *,[class*=dropdown] *,body > div *')].filter(node=>visible(node)&&directText(node)===primary);for(const node of primaryNodes){const semantic=node.closest('[role=option],li,[data-option-index],[class*=option],[class*=suggestion],[class*=result],[class*=item]');if(semantic&&visible(semantic)&&hasDirectText(semantic,subtitle))return semantic;let candidate=node.parentElement;for(let depth=0;candidate&&candidate!==document.body&&depth<6;depth++,candidate=candidate.parentElement){if(visible(candidate)&&hasDirectText(candidate,primary)&&hasDirectText(candidate,subtitle))return candidate;}}return null;}
function streetUnlocked(){const street=findInput('street')||inputCandidates('street',false)[0];return !!street&&!street.disabled&&!street.readOnly&&street.getAttribute('aria-disabled')!=='true';}
function streetNumberUnlocked(){const field=inputCandidates('streetNumber',false)[0];return !!field&&!field.disabled&&!field.readOnly&&field.getAttribute('aria-disabled')!=='true';}
async function bridgeAutocomplete(kind,value){const root=document.documentElement;const requestId=`${kind}-${Date.now()}-${Math.random()}`;root.dataset.nikasAutoRequest=requestId;root.dataset.nikasAutoKind=kind;root.dataset.nikasAutoValue=String(value);root.dataset.nikasAutoStatus='working';root.dispatchEvent(new Event('nikas:autocomplete'));const done=await waitUntil(()=>root.dataset.nikasAutoResponse===requestId&&root.dataset.nikasAutoStatus!=='working',60000);return {ok:!!done&&root.dataset.nikasAutoStatus==='ok',reason:done?(root.dataset.nikasAutoReason||'confirmation-failed'):'main-world-bridge-timeout'};}
async function chooseLocation(v){if(v==null||v==='')return false;lastLocationReason='';const bridge=await bridgeAutocomplete('city',v);if(streetUnlocked()){listingLog('city accepted because SS street selector is enabled:',v);return true;}lastLocationReason=bridge.reason;for(let attempt=0;attempt<2;attempt++){const input=findInput('location');if(!input){lastLocationReason='location-input-not-found';return false;}input.click();input.focus();setValue(input,'',false);setValue(input,v,false);let row=null;await waitUntil(()=>!!(row=locationRow(v)),5000);if(!row)continue;realClick(row);const confirmed=await waitUntil(streetUnlocked,5000);if(confirmed)return true;}return false;}
async function chooseStreet(v){if(v==null||v==='')return true;lastStreetReason='';const bridge=await bridgeAutocomplete('street',v);if(bridge.ok&&streetNumberUnlocked())return true;lastStreetReason=bridge.reason;for(let attempt=0;attempt<3;attempt++){const field=findInput('street');if(!field){lastStreetReason='street-input-not-found';return false;}if(await autocomplete('street',v)){const confirmed=await waitUntil(()=>streetNumberUnlocked()||norm(findInput('street')?.value).includes(norm(v)),5000);if(confirmed)return true;}await sleep(250);}lastStreetReason=lastStreetReason||'street-option-not-confirmed';return false;}
async function autocomplete(f,v){if(v==null||v==='')return false;const e=findInput(f);if(!e)return false;e.focus();setValue(e,v,false);await sleep(900);const w=norm(v);const er=e.getBoundingClientRect();let option;
  if(f==='location'){
    const below=[...document.querySelectorAll('[role=option],li,button,[tabindex],div,span')].filter(x=>{if(!visible(x)||!norm(x.textContent).startsWith(w))return false;const r=x.getBoundingClientRect();return r.top>=er.bottom-4&&r.top<er.bottom+320&&r.right>er.left&&r.left<er.right;}).sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return ar.top-br.top||(ar.width*ar.height-br.width*br.height);});
    option=below[0];
    if(option){let row=option.closest('[role=option],li,button,[tabindex]');if(!row){row=option;while(row.parentElement&&row.getBoundingClientRect().width<er.width*.65&&row.parentElement.getBoundingClientRect().top>=er.bottom-6)row=row.parentElement;}option=row;}
  }
  if(!option){const candidates=[...document.querySelectorAll('[role=option],[role=listbox] li,li,[class*=suggest] *,[class*=autocomplete] *,[class*=dropdown] *,[class*=option]')].filter(x=>visible(x)&&norm(x.textContent).includes(w)).sort((a,b)=>a.textContent.trim().length-b.textContent.trim().length);option=candidates.find(x=>norm(x.textContent)===w)||candidates[0];}
  if(option){realClick(option);await sleep(900);return true;}
  for(const type of ['keydown','keyup'])e.dispatchEvent(new KeyboardEvent(type,{key:'ArrowDown',code:'ArrowDown',keyCode:40,which:40,bubbles:true}));await sleep(120);for(const type of ['keydown','keyup'])e.dispatchEvent(new KeyboardEvent(type,{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));await sleep(900);return true;}
function segmentedClickTarget(choice,scope){for(let target=choice,depth=0;target&&target!==scope&&depth<5;target=target.parentElement,depth++){const rect=target.getBoundingClientRect(),card=target.matches('div')&&rect.width>=45&&rect.height>=35;if(target.matches('button,label,[role=radio],[role=button]')||getComputedStyle(target).cursor==='pointer'||card)return target;}return choice;}
function segmentChoice(f,wanted){const headings=[...document.querySelectorAll('label,legend,h1,h2,h3,h4,h5,p,span,div')].filter(x=>visible(x)&&G[f].some(n=>norm(x.textContent)===norm(n))).sort((a,b)=>a.textContent.length-b.textContent.length);for(const heading of headings){let box=heading.parentElement;for(let depth=0;box&&depth<6;depth++,box=box.parentElement){const choices=[...box.querySelectorAll('button,label,[role=radio],input[type=radio]+*,div,span,p')].filter(x=>visible(x)&&norm(x.textContent)).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length);const choice=choices.find(x=>norm(x.textContent)===wanted)||choices.find(x=>norm(x.textContent).includes(wanted));if(choice)return segmentedClickTarget(choice,box);}}
  // Fallback: the site's own heading wording may not match any G[f] alias (fragile), but the
  // wanted VALUE from data.json is known exactly. Search all choice-like elements site-wide for
  // an exact text match; only trust it when it's unambiguous.
  const globalChoices=[...document.querySelectorAll('button,label,[role=radio],input[type=radio]+*,div,span,p')].filter(x=>visible(x)&&norm(x.textContent)===wanted);
  if(globalChoices.length===1)return segmentedClickTarget(globalChoices[0],document.body);
  if(globalChoices.length>1)return segmentedClickTarget(globalChoices.sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0],document.body);
}
function associatedRadio(choice){if(!choice)return null;if(choice.matches('input[type=radio]'))return choice;const nested=choice.querySelector('input[type=radio]');if(nested)return nested;const forId=choice.htmlFor||choice.getAttribute('for');if(forId){const linked=document.getElementById(forId);if(linked&&linked.matches('input[type=radio]'))return linked;}return null;}
function choiceState(choice){if(!choice)return '';const radio=associatedRadio(choice);return JSON.stringify({checked:radio?.checked,pressed:choice.getAttribute('aria-pressed'),ariaChecked:choice.getAttribute('aria-checked'),dataState:choice.getAttribute('data-state'),className:choice.className,style:choice.getAttribute('style')});}
function choiceSelected(choice){const radio=associatedRadio(choice);return !!choice&&(radio?.checked||hasPrimaryChoiceClass(choice)||choice.getAttribute('aria-pressed')==='true'||choice.getAttribute('aria-checked')==='true'||choice.getAttribute('data-state')==='checked'||/(^|\s)(active|selected|checked)(\s|$)/i.test(String(choice.className)));}
async function segmented(f,v){if(v==null||v==='')return false;let wanted=norm(v);if(f==='condition'&&wanted===norm('\u10d2\u10d0\u10e0\u10d4\u10db\u10dd\u10dc\u10e2\u10d4\u10d1\u10e3\u10da\u10d8'))wanted=norm('\u10d0\u10ee\u10d0\u10da\u10d8 \u10d2\u10d0\u10e0\u10d4\u10db\u10dd\u10dc\u10e2\u10d4\u10d1\u10e3\u10da\u10d8');const choice=segmentChoice(f,wanted);if(!choice)return false;if(choiceSelected(choice))return true;if(isSsCreatePage())clickChoiceOnce(choice);else realClick(choice);if(await waitUntil(()=>choiceSelected(segmentChoice(f,wanted)),1000))return true;return isSsCreatePage();}
function bool(f,v){if(typeof v!=='boolean')return false;const e=[...document.querySelectorAll('input[type=checkbox]')].find(x=>matches(x,f));if(e){if(e.checked!==v)e.click();return true;}const l=[...document.querySelectorAll('label,button,[role=checkbox]')].find(x=>visible(x)&&G[f].some(n=>norm(x.textContent).includes(norm(n))));if(!l)return false;const on=l.getAttribute('aria-checked')==='true'||l.classList.contains('active')||l.classList.contains('selected');if(on!==v)l.click();return true;}
async function fill(d){
  if(isSsCreatePage()){ssAppliedExactChoices.clear();ssTransactionCardValue='';}
  const v=values(d);
  v.project=DEFAULT_PROJECT_TYPE;
  let n=await applySsCreateDefaults();
  if(isSsCreatePage())Object.assign(v,{property:'\u10d1\u10d8\u10dc\u10d0',rooms:1,balconyCount:1,bathrooms:1,buildingStatus:'\u10d0\u10ee\u10d0\u10da\u10d8 \u10d0\u10e8\u10d4\u10dc\u10d4\u10d1\u10e3\u10da\u10d8',project:'\u10d0\u10e0\u10d0\u10e1\u10e2\u10d0\u10dc\u10d3\u10d0\u10e0\u10e2\u10e3\u10da\u10d8'});
  if(v.transaction){if(!await stabilizeRentalChoices(v.transaction))throw new Error(dealSelectionError(v.transaction));n++;}
  if(isSsCreatePage()&&await applySsAdditionalInfoDefaults(v))n++;
  const handled={transaction:true};
  for(const f of ['property','buildingStatus','condition','rooms','bedrooms','balconyCount','bathrooms']){handled[f]=await segmented(f,v[f]);if(handled[f])n++;}
  handled.project=isSsCreatePage()||await selectDefaultProjectType();if(handled.project&&!isSsCreatePage())n++;
  for(const f of ['property','condition','currency'])if(!handled[f]&&await select(f,v[f]))n++;
  const locationSelected=await chooseLocation(v.location);if(locationSelected){n++;await sleep(150);}
  for(const f of ['description','price','area','rooms','bedrooms','balconyCount','bathrooms','floor','totalFloors','phone'])if(!handled[f]&&await inputVerified(f,v[f]))n++;
  for(const f of ['elevator','parking','yard'])if(bool(f,v[f]))n++;
  const dealSelected=!v.transaction||await stabilizeRentalChoices(v.transaction,1500);
  if(!dealSelected)throw new Error(dealSelectionError(v.transaction));
  if(!isSsCreatePage()&&!await selectDefaultProjectType())throw new Error(`Project type "${DEFAULT_PROJECT_TYPE}" could not be confirmed.`);
  if(isSsCreatePage()&&!await applySsAdditionalInfoDefaults(v))throw new Error('SS.ge additional information defaults could not be confirmed.');
  return {count:n,locationSelected:!v.location||locationSelected,dealSelected,transaction:v.transaction,formValues:v};
}
function decodeImage(image){if(image.dataUrl){const encoded=String(image.dataUrl).split(',')[1]||'';const binary=atob(encoded);const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes;}return new Uint8Array(image.bytes||[]);}
let lastImageDebug='not-started';
async function bridgeImages(list){const root=document.documentElement,requestId=`${Date.now()}-${Math.random().toString(36).slice(2)}`,payload=document.createElement('script');payload.type='application/json';payload.id=`nikas-images-${requestId}`;payload.textContent=JSON.stringify(list);document.documentElement.appendChild(payload);root.dataset.nikasImagesRequest=requestId;root.dataset.nikasImagesStatus='working';root.dataset.nikasImagesReason='';root.dataset.nikasImagesDebug='';root.dispatchEvent(new Event('nikas:images'));const done=await waitUntil(()=>root.dataset.nikasImagesResponse===requestId&&root.dataset.nikasImagesStatus!=='working',15000);payload.remove();lastImageDebug=done?(root.dataset.nikasImagesDebug||root.dataset.nikasImagesReason||'no-debug'):'MAIN-world image bridge timeout';listingLog('image bridge:',lastImageDebug);if(!done||root.dataset.nikasImagesStatus!=='ok')return 0;try{return Number(JSON.parse(root.dataset.nikasImagesDebug).attached)||0;}catch{return list.length;}}
function fileDragEvent(type,dataTransfer){try{return new DragEvent(type,{bubbles:true,cancelable:true,composed:true,dataTransfer});}catch{const event=new Event(type,{bubbles:true,cancelable:true,composed:true});Object.defineProperty(event,'dataTransfer',{value:dataTransfer});return event;}}
async function images(list){if(!list?.length)return 0;const bridged=await bridgeImages(list);if(bridged)return bridged;const app=document.querySelector('#create-app-images');const dropzone=app?.querySelector('[role=presentation]');const input=app?.querySelector('input[type=file][multiple]')||app?.querySelector('input[type=file]')||document.querySelector('input[type=file][multiple]');if(!input||!dropzone){lastImageDebug+=` | isolated fallback app=${!!app} input=${!!input} dropzone=${!!dropzone}`;return 0;}const dt=new DataTransfer();for(const image of list)dt.items.add(new File([decodeImage(image)],image.name,{type:image.type||'image/jpeg',lastModified:Date.now()}));const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'files')?.set;if(setter)setter.call(input,dt.files);else input.files=dt.files;input.dispatchEvent(new Event('input',{bubbles:true,composed:true}));input.dispatchEvent(new Event('change',{bubbles:true,composed:true}));await sleep(2000);return input.files?.length||0;}
let fillInProgress=false;
chrome.runtime.onMessage.addListener((m,_s,reply)=>{if(m.type!=='FILL_LISTING')return;if(fillInProgress){reply({ok:false,error:'A listing import is already running on this page.'});return;}fillInProgress=true;(async()=>{try{const result=await fill(m.payload.data),imageWatcher=createImageUiWatcher(),expectedImages=m.payload.images?.length||0;const imageCount=await images(m.payload.images);if(expectedImages&&imageCount!==expectedImages){await imageWatcher.settle(imageCount);throw new Error(`Only ${imageCount} of ${expectedImages} image(s) were attached. Debug: ${lastImageDebug}`);}await imageWatcher.settle(imageCount);result.dealSelected=await stabilizeDealAfterImages(m.payload.data);if(!result.dealSelected){reply({ok:false,error:dealSelectionError(result.transaction),filled:result.count,images:imageCount});return;}if(!isSsCreatePage()&&!await selectDefaultProjectType()){reply({ok:false,error:`Project type "${DEFAULT_PROJECT_TYPE}" could not be confirmed.`,filled:result.count,images:imageCount});return;}if(isSsCreatePage()&&!await applySsAdditionalInfoDefaults(result.formValues)){reply({ok:false,error:'SS.ge additional information defaults could not be confirmed.',filled:result.count,images:imageCount});return;}maintainSsRentalDefault(result.transaction);if(!isSsCreatePage())maintainDefaultProjectType();maintainSsAdditionalInfoDefaults(result.formValues);if(!result.locationSelected){reply({ok:false,error:`The city autocomplete option was not confirmed (${lastLocationReason||'unknown reason'}).`,filled:result.count,images:imageCount});return;}reply({ok:true,filled:result.count,images:imageCount});}catch(e){reply({ok:false,error:e.message});}finally{fillInProgress=false;}})();return true;});
